<?php
	if(isset($_GET['wordpress-factory'])) {
		if(!isset($_POST['_referrer']) || !isset($_POST['_caller'])) {
			echo "<strong>A FATAL ERROR OCCURED</strong><br/ >";
			echo "generated by: wordpress-factory plugin";
			die(); // directly dies
			return;
		} else {
			$caller = $_POST['_caller'];
			try{
				$caller::post();
			}catch(Exception $exs) {
				echo "<strong>A FATAL ERROR OCCURED</strong>";
				echo $exs;
				die();	
			}
			header('Location: '.$_POST['_referrer']);
			die();
		}
	}

